#!/usr/bin/env python3
"""Regenerate index.json from all animations/*/manifest.json files.

Usage: python generate_index.py
Run from the repo root. Writes index.json.
"""

import json
import os
import re
from datetime import date

ANIMATIONS_DIR = "animations"
README_PATH = "README.md"
REPO = "Evol-Luci/ascii-screensaver-animations"
BRANCH = "main"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/refs/heads/{BRANCH}"

GALLERY_START = "<!-- GALLERY:START — auto-generated by .github/scripts/generate_index.py, do not edit by hand -->"
GALLERY_END = "<!-- GALLERY:END -->"


def raw_url(animation_id, filename):
    return f"{RAW_BASE}/animations/{animation_id}/{filename}"


def list_files(folder):
    """Return all files in a folder recursively, relative to the folder."""
    result = []
    for dirpath, _, filenames in os.walk(folder):
        for fname in filenames:
            full = os.path.join(dirpath, fname)
            rel = os.path.relpath(full, folder)
            result.append(rel)
    return sorted(result)


def render_gallery(animations):
    if not animations:
        return "_No animations yet — be the first to submit one!_"
    lines = ["| Animation | Preview | Description |", "| --- | --- | --- |"]
    for a in sorted(animations, key=lambda a: a["id"]):
        preview = f'![{a["id"]}]({a["preview"]})' if a["preview"] else ""
        description = (a["description"] or "").replace("|", "\\|").replace("\n", " ")
        lines.append(f'| **{a["id"]}** | {preview} | {description} |')
    return "\n".join(lines)


def update_readme_gallery(animations):
    """Replace the content between the GALLERY markers in README.md. The
    markers must already exist in the file — this never creates the
    section itself, so a missing/renamed section fails loudly instead of
    silently no-op'ing."""
    if not os.path.isfile(README_PATH):
        print(f"WARNING: {README_PATH} not found — skipping gallery update.")
        return
    with open(README_PATH, encoding="utf-8") as f:
        readme = f.read()

    if GALLERY_START not in readme or GALLERY_END not in readme:
        print(f"WARNING: gallery markers not found in {README_PATH} — skipping gallery update.")
        return

    pattern = re.compile(
        re.escape(GALLERY_START) + r".*?" + re.escape(GALLERY_END), re.DOTALL
    )
    replacement = GALLERY_START + "\n\n" + render_gallery(animations) + "\n\n" + GALLERY_END
    new_readme = pattern.sub(lambda _: replacement, readme, count=1)

    if new_readme != readme:
        with open(README_PATH, "w", encoding="utf-8") as f:
            f.write(new_readme)
        print(f"Updated gallery in {README_PATH}.")
    else:
        print(f"{README_PATH} gallery already current.")


def main():
    animations = []
    anim_dir = ANIMATIONS_DIR

    if not os.path.isdir(anim_dir):
        print(f"WARNING: {anim_dir}/ directory not found. No animations indexed.")
        index = {"version": 1, "updated": date.today().isoformat(), "animations": []}
        with open("index.json", "w", encoding="utf-8") as f:
            json.dump(index, f, indent=2)
            f.write("\n")
        print("Generated empty index.json.")
        update_readme_gallery([])
        return

    for name in sorted(os.listdir(anim_dir)):
        folder = os.path.join(anim_dir, name)
        if not os.path.isdir(folder):
            continue
        manifest_path = os.path.join(folder, "manifest.json")
        if not os.path.isfile(manifest_path):
            print(f"WARNING: skipping {name} — no manifest.json")
            continue
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)
        except json.JSONDecodeError as e:
            print(f"WARNING: skipping {name} — invalid manifest.json: {e}")
            continue

        files = [raw_url(name, f) for f in list_files(folder)]
        preview_file = manifest.get("preview", "")
        preview_url = raw_url(name, preview_file) if preview_file else ""

        entry = {
            "id": manifest["id"],
            "name": manifest["name"],
            "description": manifest.get("description", ""),
            "author": manifest.get("author", ""),
            "version": manifest.get("version", "1.0.0"),
            "preview": preview_url,
            "params": manifest.get("params", []),
            "files": files,
        }
        animations.append(entry)

    index = {
        "version": 1,
        "updated": date.today().isoformat(),
        "animations": animations,
    }

    with open("index.json", "w", encoding="utf-8") as f:
        json.dump(index, f, indent=2)
        f.write("\n")

    print(f"Generated index.json with {len(animations)} animations.")
    update_readme_gallery(animations)


if __name__ == "__main__":
    main()
